spring.application.name=yoni
server.port=8081
spring.datasource.url=jdbc:postgresql://ep-super-feather-ab4y0cbx-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_wifF4jSX8BrW

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.hikari.data-source-properties.sslmode=require
spring.datasource.hikari.data-source-properties.channelBinding=require